
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure(9909fced-8203-44b6-af68-11f833a37e60)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az config set extension.use_dynamic_install=yes_without_prompt'
  displayName: 'Az Config Dynamic Install'
  continueOnError: true

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure(9909fced-8203-44b6-af68-11f833a37e60)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'echo $(PAT) | az login'
  displayName: 'Az Login'
  continueOnError: true
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '1.2.3'
  displayName: Instalacion Terraform

- task: TerraformCLI@0
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'azure(9909fced-8203-44b6-af68-11f833a37e60)'
    allowTelemetryCollection: true
  displayName: Terraform init
  continueOnError: true
- task: TerraformCLI@0
  inputs:
    command: 'plan'
    environmentServiceName: 'azure(9909fced-8203-44b6-af68-11f833a37e60)'
    commandOptions: '-var ssh_key="$SSH_KEY"'
    allowTelemetryCollection: true
  displayName: Terraform plan
  continueOnError: true
- task: TerraformCLI@0
  inputs:
    command: 'import'
    environmentServiceName: 'azure(9909fced-8203-44b6-af68-11f833a37e60)'
    runAzLogin: true
    commandOptions: '-var ssh_key="$SSH_KEY"'
    allowTelemetryCollection: true
    resourceAddress: 'module.cluster.azurerm_resource_group.aks-getting-started'
    resourceId: '/subscriptions/9909fced-8203-44b6-af68-11f833a37e60/resourceGroups/aks-getting-started'
  continueOnError: true
  displayName: Terraform import
  
- task: TerraformCLI@0
  inputs:
    command: 'apply'
    environmentServiceName: 'azure(9909fced-8203-44b6-af68-11f833a37e60)'
    runAzLogin: true
    #commandOptions: '-var ssh_key="$SSH_KEY"'
    allowTelemetryCollection: true
  displayName: Terraform apply
  continueOnError: true